application: grounded-plane-92507
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /(.+\.(html|js|css|gif|png|jpg|svg))$
  static_files: \1
  upload: .+\.(html|js|css|gif|png|jpg|svg)$
  application_readable: true

# PHP Scriptbestanden.
- url: /(.+\.php)$
  script: \1
  
- url: /
  static_files: index.html
  upload: index.html
  application_readable: true
